/*
 * Copyright (c) 2020-2020, Koninklijke Philips N.V., https://www.philips.com
 * SPDX-License-Identifier: MIT
 */

/// Copied from SPDX license identifier table v3 of April 22, 2020.
final dictionary = <String, String>{
  '3dfx glide license': 'Glide',
  'abstyles license': 'Abstyles',
  'academic free license v1.1': 'AFL-1.1',
  'academic free license v1.2': 'AFL-1.2',
  'academic free license v2.0': 'AFL-2.0',
  'academic free license v2.1': 'AFL-2.1',
  'academic free license v3.0': 'AFL-3.0',
  'academy of motion picture arts and sciences bsd': 'AMPAS',
  'adaptive public license 1.0': 'APL-1.0',
  'adobe glyph list license': 'Adobe-Glyph',
  'adobe postscript AFM License': 'APAFML',
  'adobe systems incorporated source code license agreement': 'Adobe-2006',
  'affero general public license v1.0 only': 'AGPL-1.0-only',
  'affero general public license v1.0 or later': 'AGPL-1.0-or-later',
  'afmparse license': 'Afmparse',
  'aladdin free public license': 'Aladdin',
  'amazon digital services license': 'ADSL',
  'amd\'s plpa_map.c license': 'AMDPLPA',
  'antlr software rights notice': 'ANTLR-PD',
  'apache license 1.0': 'Apache-1.0',
  'apache license 1.1': 'Apache-1.1',
  'apache license 2.0': 'Apache-2.0',
  'apple mit license': 'AML',
  'apple public source license 1.0': 'APSL-1.0',
  'apple public source license 1.1': 'APSL-1.1',
  'apple public source license 1.2': 'APSL-1.2',
  'apple public source license 2.0': 'APSL-2.0',
  'artistic license 1.0': 'Artistic-1.0',
  'artistic license 1.0 (perl)': 'Artistic-1.0-Perl',
  'artistic license 1.0 w/clause 8': 'Artistic-1.0-cl8',
  'artistic license 2.0': 'Artistic-2.0',
  'attribution assurance license': 'AAL',
  'bahyph license': 'Bahyph',
  'barr license': 'Barr',
  'beerware license': 'Beerware',
  'bittorrent open source license v1.0': 'BitTorrent-1.0',
  'bittorrent open source license v1.1': 'BitTorrent-1.1',
  'blue oak model license 1.0.0': 'BlueOak-1.0.0',
  'boost software license 1.0': 'BSL-1.0',
  'borceux license': 'Borceux',
  'bsd 1-clause license': 'BSD-1-Clause',
  'bsd 2-clause "simplified" license': 'BSD-2-Clause',
  'bsd 2-clause freebsd license': 'BSD-2-Clause-FreeBSD',
  'bsd 2-clause netbsd license': 'BSD-2-Clause-NetBSD',
  'bsd 3-clause "new" or "revised" license': 'BSD-3-Clause',
  'bsd 3-clause clear license': 'BSD-3-Clause-Clear',
  'bsd 3-clause no nuclear license': 'BSD-3-Clause-No-Nuclear-License',
  'bsd 3-clause no nuclear license 2014':
      'BSD-3-Clause-No-Nuclear-License-2014',
  'bsd 3-clause no nuclear warranty': 'BSD-3-Clause-No-Nuclear-Warranty',
  'bsd 3-clause open mpi variant': 'BSD-3-Clause-Open-MPI',
  'bsd 4-clause "original" or "old" license': 'BSD-4-Clause',
  'bsd protection license': 'BSD-Protection',
  'bsd source code attribution': 'BSD-Source-Code',
  'bsd with attribution': 'BSD-3-Clause-Attribution',
  'bsd zero clause license': '0BSD',
  'bsd-2-clause plus patent license': 'BSD-2-Clause-Patent',
  'bsd-4-clause (university of california-specific)': 'BSD-4-Clause-UC',
  'bzip2 and libbzip2 license v1.0.5': 'bzip2-1.0.5',
  'bzip2 and libbzip2 license v1.0.6': 'bzip2-1.0.6',
  'caldera license': 'Caldera',
  'cecill free software license agreement v1.0': 'CECILL-1.0',
  'cecill free software license agreement v1.1': 'CECILL-1.1',
  'cecill free software license agreement v2.0': 'CECILL-2.0',
  'cecill free software license agreement v2.1': 'CECILL-2.1',
  'cecill-b free software license agreement': 'CECILL-B',
  'cecill-c free software license agreement': 'CECILL-C',
  'cern open hardware licence v1.1': 'CERN-OHL-1.1',
  'cern open hardware licence v1.2': 'CERN-OHL-1.2',
  'clarified artistic license': 'ClArtistic',
  'cmu license': 'mIT-CMU',
  'cnri jython license': 'CNRI-Jython',
  'cnri python license': 'CNRI-Python',
  'cnri python open source gpl compatible license agreement':
      'CNRI-Python-GPL-Compatible',
  'code project open license 1.02': 'CPOL-1.02',
  'common development and distribution license 1.0': 'CDDL-1.0',
  'common development and distribution license 1.1': 'CDDL-1.1',
  'common public attribution license 1.0': 'CPAL-1.0',
  'common public license 1.0': 'CPL-1.0',
  'community data license agreement permissive 1.0': 'CDLA-Permissive-1.0',
  'community data license agreement sharing 1.0': 'CDLA-Sharing-1.0',
  'computer associates trusted open source license 1.1': 'CATOSL-1.1',
  'condor public license v1.1': 'Condor-1.1',
  'copyleft-next 0.3.0': 'copyleft-next-0.3.0',
  'copyleft-next 0.3.1': 'copyleft-next-0.3.1',
  'creative commons attribution 1.0 generic': 'CC-BY-1.0',
  'creative commons attribution 1.0': 'CC-BY-1.0', // Black Duck specific
  'creative commons attribution 2.0 generic': 'CC-BY-2.0',
  'creative commons attribution 2.0': 'CC-BY-2.0', // Black Duck specific
  'creative commons attribution 2.5 generic': 'CC-BY-2.5',
  'creative commons attribution 2.5': 'CC-BY-2.5', // Black Duck specific
  'creative commons attribution 3.0 unported': 'CC-BY-3.0',
  'creative commons attribution 3.0': 'CC-BY-3.0', // Black Duck specific
  'creative commons attribution 4.0 international': 'CC-BY-4.0',
  'creative commons attribution 4.0': 'CC-BY-4.0', // Black Duck specific
  'creative commons attribution no derivatives 1.0 generic': 'CC-BY-ND-1.0',
  'creative commons attribution no derivatives 2.0 generic': 'CC-BY-ND-2.0',
  'creative commons attribution no derivatives 2.5 generic': 'CC-BY-ND-2.5',
  'creative commons attribution no derivatives 3.0 unported': 'CC-BY-ND-3.0',
  'creative commons attribution no derivatives 4.0 international':
      'CC-BY-ND-4.0',
  'creative commons attribution non commercial 1.0 generic': 'CC-BY-NC-1.0',
  'creative commons attribution non commercial 2.0 generic': 'CC-BY-NC-2.0',
  'creative commons attribution non commercial 2.5 generic': 'CC-BY-NC-2.5',
  'creative commons attribution non commercial 3.0 unported': 'CC-BY-NC-3.0',
  'creative commons attribution non commercial 4.0 international':
      'CC-BY-NC-4.0',
  'creative commons attribution non commercial no derivatives 1.0 generic':
      'CC-BY-NC-ND-1.0',
  'creative commons attribution non commercial no derivatives 2.0 generic':
      'CC-BY-NC-ND-2.0',
  'creative commons attribution non commercial no derivatives 2.5 generic':
      'CC-BY-NC-ND-2.5',
  'creative commons attribution non commercial no derivatives 3.0 unported':
      'CC-BY-NC-ND-3.0',
  'creative commons attribution non commercial no derivatives 4.0 international':
      'CC-BY-NC-ND-4.0',
  'creative commons attribution non commercial share alike 1.0 generic':
      'CC-BY-NC-SA-1.0',
  'creative commons attribution non commercial share alike 2.0 generic':
      'CC-BY-NC-SA-2.0',
  'creative commons attribution non commercial share alike 2.5 generic':
      'CC-BY-NC-SA-2.5',
  'creative commons attribution non commercial share alike 3.0 unported':
      'CC-BY-NC-SA-3.0',
  'creative commons attribution non commercial share alike 4.0 international':
      'CC-BY-NC-SA-4.0',
  'creative commons attribution share alike 1.0 generic': 'CC-BY-SA-1.0',
  'creative commons attribution share alike 2.0 generic': 'CC-BY-SA-2.0',
  'creative commons attribution share alike 2.5 generic': 'CC-BY-SA-2.5',
  'creative commons attribution share alike 3.0 unported': 'CC-BY-SA-3.0',
  'creative commons attribution share alike 4.0 international': 'CC-BY-SA-4.0',
  'creative commons public domain dedication and certification': 'CC-PDDC',
  'creative commons zero v1.0 universal': 'CC0-1.0',
  'crossword license': 'Crossword',
  'crystalstacker license': 'CrystalStacker',
  'cua office public license v1.0': 'CUA-OPL-1.0',
  'cube license': 'Cube',
  'curl license': 'curl',
  'deutsche freie software lizenz': 'D-FSL-1.0',
  'diffmark license': 'diffmark',
  'do what the f*ck you want to public license': 'WTFPL',
  'doc license': 'dOC',
  'dotseqn license': 'Dotseqn',
  'dsdp license': 'DSDP',
  'dvipdfm license': 'dvipdfm',
  'eclipse public license 1.0': 'EPL-1.0',
  'eclipse public license 2.0': 'EPL-2.0',
  'educational community license v1.0': 'ECL-1.0',
  'educational community license v2.0': 'ECL-2.0',
  'egenix.com public license 1.1.0': 'eGenix',
  'eiffel forum license v1.0': 'EFL-1.0',
  'eiffel forum license v2.0': 'EFL-2.0',
  'enlightenment license (e16)': 'MIT-advertising',
  'enna license': 'MIT-enna',
  'entessa public license v1.0': 'Entessa',
  'erlang public license v1.1': 'ErlPL-1.1',
  'etalab open license 2.0': 'etalab-2.0',
  'eu datagrid software license': 'EUDatagrid',
  'european union public license 1.0': 'EUPL-1.0',
  'european union public license 1.1': 'EUPL-1.1',
  'european union public license 1.2': 'EUPL-1.2',
  'eurosym license': 'Eurosym',
  'fair license': 'Fair',
  'feh license': 'mIT-feh',
  'frameworx open license 1.0': 'Frameworx-1.0',
  'freeimage public license v1.0': 'FreeImage',
  'freetype project license': 'FTL',
  'fsf all permissive license': 'FSFAP',
  'fsf unlimited license': 'FSFUL',
  'fsf unlimited license (with license retention)': 'FSFULLR',
  'giftware license': 'Giftware',
  'gl2ps license': 'GL2PS',
  'glulxe license': 'Glulxe',
  'gnu affero general public license v3.0 only': 'AGPL-3.0-only',
  'gnu affero general public license v3.0 or later': 'AGPL-3.0-or-later',
  'gnu free documentation license v1.1 only': 'GFDL-1.1-only',
  'gnu free documentation license v1.1 or later': 'GFDL-1.1-or-later',
  'gnu free documentation license v1.2 only': 'GFDL-1.2-only',
  'gnu free documentation license v1.2 or later': 'GFDL-1.2-or-later',
  'gnu free documentation license v1.3 only': 'GFDL-1.3-only',
  'gnu free documentation license v1.3 or later': 'GFDL-1.3-or-later',
  'gnu general public license v1.0 only': 'GPL-1.0-only',
  'gnu general public license v1.0 or later': 'GPL-1.0-or-later',
  'gnu general public license v2.0 only': 'GPL-2.0-only',
  'gnu general public license v2.0 or later': 'GPL-2.0-or-later',
  'gnu general public license v3.0 only': 'GPL-3.0-only',
  'gnu general public license v3.0 or later': 'GPL-3.0-or-later',
  'gnu lesser general public license v2.1 only': 'LGPL-2.1-only',
  'gnu lesser general public license v2.1 or later': 'LGPL-2.1-or-later',
  'gnu lesser general public license v3.0 only': 'LGPL-3.0-only',
  'gnu lesser general public license v3.0 or later': 'LGPL-3.0-or-later',
  'gnu library general public license v2 only': 'LGPL-2.0-only',
  'gnu library general public license v2 or later': 'LGPL-2.0-or-later',
  'gnuplot license': 'gnuplot',
  'gsoap public license v1.3b': 'gSOAP-1.3b',
  'haskell language report license': 'HaskellReport',
  'historical permission notice and disclaimer': 'HPND',
  'historical permission notice and disclaimer - sell variant':
      'HPND-sell-variant',
  'ibm powerpc initialization and boot software': 'IBM-pibs',
  'ibm public license v1.0': 'IPL-1.0',
  'icu license': 'iCU',
  'imagemagick license': 'ImageMagick',
  'imatix standard function library agreement': 'iMatix',
  'imlib2 license': 'Imlib2',
  'independent jpeg group license': 'IJG',
  'info-zip license': 'Info-ZIP',
  'intel acpi software license agreement': 'Intel-ACPI',
  'intel open source license': 'Intel',
  'interbase public license v1.0': 'Interbase-1.0',
  'ipa font license': 'IPA',
  'isc license': 'ISC',
  'japan network information center license': 'JPNIC',
  'jasper license': 'JasPer-2.0',
  'json license': 'JSON',
  'latex project public license v1.0': 'LPPL-1.0',
  'latex project public license v1.1': 'LPPL-1.1',
  'latex project public license v1.2': 'LPPL-1.2',
  'latex project public license v1.3a': 'LPPL-1.3a',
  'latex project public license v1.3c': 'LPPL-1.3c',
  'latex2e license': 'Latex2e',
  'lawrence berkeley national labs bsd variant license': 'BSD-3-Clause-LBNL',
  'leptonica license': 'Leptonica',
  'lesser general public license for linguistic resources': 'LGPLLR',
  'libpng license': 'Libpng',
  'libselinux public domain notice': 'libselinux-1.0',
  'libtiff license': 'libtiff',
  'licence art libre 1.2': 'LAL-1.2',
  'licence art libre 1.3': 'LAL-1.3',
  'licence libre du québec – permissive version 1.1': 'LiLiQ-P-1.1',
  'licence libre du québec – réciprocité forte version 1.1': 'LiLiQ-Rplus-1.1',
  'licence libre du québec – réciprocité version 1.1': 'LiLiQ-R-1.1',
  'linux kernel variant of openib.org license': 'Linux-OpenIB',
  'lucent public license v1.02': 'LPL-1.02',
  'lucent public license version 1.0': 'LPL-1.0',
  'makeindex license': 'MakeIndex',
  'matrix template library license': 'MTLL',
  'microsoft public license': 'MS-PL',
  'microsoft reciprocal license': 'MS-RL',
  'mit +no-false-attribs license': 'MITNFA',
  'mit license': 'MIT',
  'mit no attribution': 'MIT-0',
  'motosoto license': 'Motosoto',
  'mozilla public license 1.0': 'MPL-1.0',
  'mozilla public license 1.1': 'MPL-1.1',
  'mozilla public license 2.0': 'MPL-2.0',
  'mozilla public license 2.0 (no copyleft exception)':
      'MPL-2.0-no-copyleft-exception',
  'mpich2 license': 'mpich2',
  'mulan permissive software license, version 1': 'MulanPSL-1.0',
  'multics license': 'Multics',
  'mup license': 'Mup',
  'nasa open source agreement 1.3': 'NASA-1.3',
  'naumen public license': 'Naumen',
  'net boolean public license v1': 'NBPL-1.0',
  'net-snmp license': 'Net-SNMP',
  'netcdf license': 'NetCDF',
  'nethack general public license': 'NGPL',
  'netizen open source license': 'NOSL',
  'netscape public license v1.0': 'NPL-1.0',
  'netscape public license v1.1': 'NPL-1.1',
  'newsletr license': 'Newsletr',
  'no limit public license': 'NLPL',
  'nokia open source license': 'Nokia',
  'non-profit open software license 3.0': 'NPOSL-3.0',
  'norwegian licence for open government data': 'NLOD-1.0',
  'noweb license': 'Noweb',
  'nrl license': 'NRL',
  'ntp license': 'NTP',
  'ntp no attribution': 'NTP-0',
  'oclc research public license 2.0': 'OCLC-2.0',
  'odc open database license v1.0': 'ODbL-1.0',
  'odc public domain dedication & license 1.0': 'PDDL-1.0',
  'open cascade technology public license': 'OCCT-PL',
  'open data commons attribution license v1.0': 'ODC-By-1.0',
  'open government licence - canada': 'OGL-Canada-2.0',
  'open government licence v1.0': 'OGL-UK-1.0',
  'open government licence v2.0': 'OGL-UK-2.0',
  'open government licence v3.0': 'OGL-UK-3.0',
  'open group test suite license': 'OGTSL',
  'open ldap public license 2.2.2': 'OLDAP-2.2.2',
  'open ldap public license v1.1': 'OLDAP-1.1',
  'open ldap public license v1.2': 'OLDAP-1.2',
  'open ldap public license v1.3': 'OLDAP-1.3',
  'open ldap public license v1.4': 'OLDAP-1.4',
  'open ldap public license v2.0 (or possibly 2.0a and 2.0b)': 'OLDAP-2.0',
  'open ldap public license v2.0.1': 'OLDAP-2.0.1',
  'open ldap public license v2.1': 'OLDAP-2.1',
  'open ldap public license v2.2': 'OLDAP-2.2',
  'open ldap public license v2.2.1': 'OLDAP-2.2.1',
  'open ldap public license v2.3': 'OLDAP-2.3',
  'open ldap public license v2.4': 'OLDAP-2.4',
  'open ldap public license v2.5': 'OLDAP-2.5',
  'open ldap public license v2.6': 'OLDAP-2.6',
  'open ldap public license v2.7': 'OLDAP-2.7',
  'open ldap public license v2.8': 'OLDAP-2.8',
  'open market license': 'OML',
  'open public license v1.0': 'OPL-1.0',
  'open software license 1.0': 'OSL-1.0',
  'open software license 1.1': 'OSL-1.1',
  'open software license 2.0': 'OSL-2.0',
  'open software license 2.1': 'OSL-2.1',
  'open software license 3.0': 'OSL-3.0',
  'openssl license': 'OpenSSL',
  'oset public license version 2.1': 'OSET-PL-2.1',
  'php license v3.0': 'PHP-3.0',
  'php license v3.01': 'PHP-3.01',
  'plexus classworlds license': 'Plexus',
  'png reference library version 2': 'libpng-2.0',
  'postgresql license': 'PostgreSQL',
  'psfrag license': 'psfrag',
  'psutils license': 'psutils',
  'python license 2.0': 'Python-2.0',
  'python software foundation license 2.0': 'PSF-2.0',
  'q public license 1.0': 'QPL-1.0',
  'qhull license': 'Qhull',
  'rdisc license': 'Rdisc',
  'realnetworks public source license v1.0': 'RPSL-1.0',
  'reciprocal public license 1.1': 'RPL-1.1',
  'reciprocal public license 1.5': 'RPL-1.5',
  'red hat ecos public license v1.1': 'RHeCos-1.1',
  'ricoh source code public license': 'RSCPL',
  'rsa message-digest license': 'RSA-MD',
  'ruby license': 'Ruby',
  'sax public domain notice': 'SAX-PD',
  'saxpath license': 'Saxpath',
  'scea shared source license': 'SCEA',
  'scheme widget library (swl) software license agreement': 'SWL',
  'secure messaging protocol public license': 'SMPPL',
  'sendmail license': 'Sendmail',
  'sendmail license 8.23': 'Sendmail-8.23',
  'server side public license, v 1': 'SSPL-1.0',
  'sgi free software license b v1.0': 'SGI-B-1.0',
  'sgi free software license b v1.1': 'SGI-B-1.1',
  'sgi free software license b v2.0': 'SGI-B-2.0',
  'sil open font license 1.0': 'OFL-1.0',
  'sil open font license 1.0 with no reserved font name': 'OFL-1.0-no-RFN',
  'sil open font license 1.0 with reserved font name': 'OFL-1.0-RFN',
  'sil open font license 1.1': 'OFL-1.1',
  'sil open font license 1.1 with no reserved font name': 'OFL-1.1-no-RFN',
  'sil open font license 1.1 with reserved font name': 'OFL-1.1-RFN',
  'simple public license 2.0': 'SimPL-2.0',
  'sleepycat license': 'Sleepycat',
  'snia public license 1.1': 'SNIA',
  'solderpad hardware license v0.5': 'SHL-0.5',
  'solderpad hardware license, version 0.51': 'SHL-0.51',
  'spencer license 86': 'Spencer-86',
  'spencer license 94': 'Spencer-94',
  'spencer license 99': 'Spencer-99',
  'sqlite blessing': 'blessing',
  'ssh openssh license': 'SSH-OpenSSH',
  'ssh short notice': 'SSH-short',
  'standard ml of new jersey license': 'SMLNJ',
  'sugarcrm public license v1.1.3': 'SugarCRM-1.1.3',
  'sun industry standards source license v1.1': 'SISSL',
  'sun industry standards source license v1.2': 'SISSL-1.2',
  'sun public license v1.0': 'SPL-1.0',
  'sybase open watcom public license 1.0': 'Watcom-1.0',
  'tapr open hardware license v1.0': 'TAPR-OHL-1.0',
  'tcl/tk license': 'TCL',
  'tcp wrappers license': 'TCP-wrappers',
  'technische universitaet berlin license 1.0': 'TU-Berlin-1.0',
  'technische universitaet berlin license 2.0': 'TU-Berlin-2.0',
  'the miros licence': 'MirOS',
  'the parity public license 6.0.0': 'Parity-6.0.0',
  'the unlicense': 'Unlicense',
  'tmate open source license': 'TMate',
  'torque v2.5+ software license v1.1': 'TORQUE-1.1',
  'trusster open source license': 'toSL',
  'unicode license agreement - data files and Software (2015)':
      'Unicode-DFS-2015',
  'unicode license agreement - data files and Software (2016)':
      'Unicode-DFS-2016',
  'unicode terms of use': 'Unicode-TOU',
  'universal permissive license v1.0': 'UPL-1.0',
  'university of illinois/ncsa open source license': 'NCSA',
  'upstream compatibility license v1.0': 'UCL-1.0',
  'vim license': 'Vim',
  'vostrom public license for open source': 'VOSTROM',
  'vovida software license v1.0': 'VSL-1.0',
  'w3c software notice and document license (2015-05-13)': 'W3C-20150513',
  'w3c software notice and license (1998-07-20)': 'W3C-19980720',
  'w3c software notice and license (2002-12-31)': 'W3C',
  'wsuipa license': 'Wsuipa',
  'x.net license': 'Xnet',
  'x11 license': 'X11',
  'xerox license': 'Xerox',
  'xfree86 license 1.1': 'XFree86-1.1',
  'xinetd license': 'xinetd',
  'xpp license': 'xpp',
  'xskat license': 'XSkat',
  'yahoo! public license v1.0': 'YPL-1.0',
  'yahoo! public license v1.1': 'YPL-1.1',
  'zed license': 'Zed',
  'zend license v2.0': 'Zend-2.0',
  'zimbra public license v1.3': 'Zimbra-1.3',
  'zimbra public license v1.4': 'Zimbra-1.4',
  'zlib license': 'Zlib',
  'zlib/libpng license with acknowledgement': 'zlib-acknowledgement',
  'zope public license 1.1': 'ZPL-1.1',
  'zope public license 2.0': 'ZPL-2.0',
  'zope public license 2.1': 'ZPL-2.1',
};

// DEPRECATED licenses for SPDX
final deprecated = <String, String>{
  'GNU General Public License v3.0 w/GCC Runtime Library exception':
      'GPL-3.0-or-later',
  'GPL-3.0-with-GCC-exception': 'GPL-3.0-or-later',
  'GNU General Public License v3.0 w/Autoconf exception': 'GPL-3.0-or-later',
  'GPL-3.0-with-autoconf-exception': 'GPL-3.0-or-later',
  'GNU General Public License v2.0 w/Font exception': 'GPL-2.0-or-later',
  'GPL-2.0-with-font-exception': 'GPL-2.0-or-later',
  'GNU General Public License v2.0 w/Autoconf exception': 'GPL-2.0-or-later',
  'GPL-2.0-with-autoconf-exception': 'GPL-2.0-or-later',
  // 'Nunit License': 'Nunit',
  'LGPL-2.0+': 'LGPL-2.0-or-later',
  'GNU Affero General Public License v3.0': 'AGPL-3.0-only',
  'AGPL-3.0': 'AGPL-3.0-only',
  'GPL-3.0+': 'GPL-3.0-or-later',
  'Affero General Public License v1.0': 'AGPL-1.0-only',
  'AGPL-1.0': 'AGPL-1.0-only',
  'LGPL-2.1': 'LGPL-2.1-only',
  'GNU Free Documentation License v1.2': 'GFDL-1.2-only',
  'GFDL-1.2': 'GFDL-1.2-only',
  'GPL-1.0+': 'GPL-1.0-or-later',
  'GNU Library General Public License v2.1 or later': 'LGPL-2.1-or-later',
  'LGPL-2.1+': 'LGPL-2.1-or-later',
  'LGPL-3.0': 'LGPL-3.0-only',
  'GNU General Public License v2.0 w/Classpath exception': 'GPL-2.0-or-later',
  'GPL-2.0-with-classpath-exception': 'GPL-2.0-or-later',
  'LGPL-3.0+': 'LGPL-3.0-or-later',
  // 'wxWindows Library License': 'wxWindows',
  'GNU Free Documentation License v1.1': 'GFDL-1.1-only',
  'GFDL-1.1': 'GFDL-1.1-only',
  // 'eCos license version 2.0': 'eCos-2.0',
  'LGPL-2.0': 'LGPL-2.0-only',
  // 'Standard ML of New Jersey License': 'StandardML-NJ',
  'GPL-1.0': 'GPL-1.0-only',
  'GNU General Public License v2.0 w/GCC Runtime Library exception':
      'GPL-2.0-or-later',
  'GPL-2.0-with-GCC-exception': 'GPL-2.0-or-later',
  'GPL-2.0': 'GPL-2.0-only',
  'GNU Free Documentation License v1.3': 'GFDL-1.3-only',
  'GFDL-1.3': 'GFDL-1.3-only',
  'GNU General Public License v2.0 w/Bison exception': 'GPL-2.0-or-later',
  'GPL-2.0-with-bison-exception': 'GPL-2.0-or-later',
  'GPL-2.0+': 'GPL-2.0-or-later',
  'GPL-3.0': 'GPL-3.0-only',
};
